
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.LobbyV2
{
    using UnityEngine.Networking;
using Hathora.Models.Shared;
    using System.Collections.Generic;
    public class CreateLobbyResponse {
        public string? ContentType { get; set; }
        
        public string? CreateLobby400ApplicationJSONString { get; set; }
        
        public string? CreateLobby401ApplicationJSONString { get; set; }
        
        public string? CreateLobby404ApplicationJSONString { get; set; }
        
        public string? CreateLobby422ApplicationJSONString { get; set; }
        
        public string? CreateLobby429ApplicationJSONString { get; set; }
        
        public string? CreateLobby500ApplicationJSONString { get; set; }
        
        public Lobby? Lobby { get; set; }
        
        public int StatusCode { get; set; }
        
        public UnityWebRequest? RawResponse { get; set; }
        
    }
}