
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.LobbyV2
{
    using UnityEngine.Networking;
using Hathora.Models.Shared;
    using System.Collections.Generic;
    public class SetLobbyStateResponse {
        public string? ContentType { get; set; }
        
    /// <summary>
    /// Ok
    /// </summary>
        public Lobby? Lobby { get; set; }
        
        public string? SetLobbyState404ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public UnityWebRequest? RawResponse { get; set; }
        
        public string? SetLobbyState422ApplicationJSONString { get; set; }
        
    }
}