
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.LobbyV2
{
    using System;
using UnityEngine.Networking;
using System.Text;
using Newtonsoft.Json;
using Hathora.Models.Shared;
using Hathora.Utils;
    using System.Collections.Generic;
    public class SetLobbyStateRequest
    {
        
        [JsonProperty("SetLobbyStateRequest")]
        public SetLobbyStateRequest SetLobbyStateRequestValue { get; set; }
        
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("roomId")]
        public string RoomId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, SetLobbyStateRequest value, string baseUrl)
        {
            if("SetLobbyState" == operationId)
            {
                
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var roomId = PathParamSerializer.Serialize("simple", false, value.RoomId);
                string json = JsonConvert.SerializeObject(value, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});var urlString = baseUrl + $"/lobby/v2/{appId}/setState/{roomId}";// #request-debugging post TODO: work in progress
                UnityWebRequest message;message = UnityWebRequest.Post(urlString, json, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [SetLobbyStateRequest]");
        }
    }
}