
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.AppV1
{
    using UnityEngine.Networking;
using Hathora.Models.Shared;
    using System.Collections.Generic;
    public class CreateAppResponse {
        public Application? Application { get; set; }
        
        public string? ContentType { get; set; }
        
        public string? CreateApp422ApplicationJSONString { get; set; }
        
        public string? CreateApp500ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public UnityWebRequest? RawResponse { get; set; }
        
    }
}