
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.RoomV2
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using Hathora.Utils;
    using System.Collections.Generic;
    public class GetInactiveRoomsForProcessRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("processId")]
        public string ProcessId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, GetInactiveRoomsForProcessRequest value, string baseUrl)
        {
            if("GetInactiveRoomsForProcess" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var processId = PathParamSerializer.Serialize("simple", false, value.ProcessId);var urlString = baseUrl + $"/rooms/v2/{appId}/list/{processId}/inactive";var message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [GetInactiveRoomsForProcessRequest]");
        }
    }
}