
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.BuildV1
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    public class RunBuildRequestBody
    {
        
        [JsonProperty("file")]
        public RunBuildRequestBodyFile File { get; set; }
        
    }
}