
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.BuildV1
{
    using System.Net.Http;
using SDK.Models.Shared;
    
    public class CreateBuildResponse {
        public Build? Build { get; set; }
        
        public string? ContentType { get; set; }
        
        public string? CreateBuild404ApplicationJSONString { get; set; }
        
        public string? CreateBuild500ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}