
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.BuildV1
{
    using System.Net.Http;
    
    public class DeleteBuildResponse {
        public string? ContentType { get; set; }
        
        public string? DeleteBuild404ApplicationJSONString { get; set; }
        
        public string? DeleteBuild422ApplicationJSONString { get; set; }
        
        public string? DeleteBuild500ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}