
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.AuthV1
{
    using UnityEngine.Networking;
using Hathora.Models.Shared;
    using System.Collections.Generic;
    public class LoginGoogleResponse {
        public string? ContentType { get; set; }
        
        public string? LoginGoogle401ApplicationJSONString { get; set; }
        
        public string? LoginGoogle404ApplicationJSONString { get; set; }
        
    /// <summary>
    /// Ok
    /// </summary>
        public LoginResponse? LoginResponse { get; set; }
        
        public int StatusCode { get; set; }
        
        public UnityWebRequest? RawResponse { get; set; }
        
    }
}