
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.AuthV1
{
    using System;
using UnityEngine.Networking;
using System.Text;
using Newtonsoft.Json;
using Hathora.Models.Shared;
using Hathora.Utils;
    using System.Collections.Generic;
    public class LoginNicknameRequest
    {
        
        [JsonProperty("LoginNicknameRequest")]
        public LoginNicknameRequest LoginNicknameRequestValue { get; set; }
        
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, LoginNicknameRequest value, string baseUrl)
        {
            if("LoginNickname" == operationId)
            {
                
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                string json = JsonConvert.SerializeObject(value, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});var urlString = baseUrl + $"/auth/v1/{appId}/login/nickname";// #request-debugging post TODO: work in progress
                UnityWebRequest message;message = UnityWebRequest.Post(urlString, json, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [LoginNicknameRequest]");
        }
    }
}