
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.AuthV1
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using Hathora.Utils;
    using System.Collections.Generic;
    public class LoginAnonymousRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, LoginAnonymousRequest value, string baseUrl)
        {
            if("LoginAnonymous" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);var urlString = baseUrl + $"/auth/v1/{appId}/login/anonymous";// #request-debugging post TODO: work in progress
                UnityWebRequest message;// cannot make a HttpMethod Post call in Unity without content (?)
                message = new UnityWebRequest(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [LoginAnonymousRequest]");
        }
    }
}