
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.RoomV2
{
    using System.Net.Http;
using SDK.Models.Shared;
    
    public class CreateRoomResponse {
        public ConnectionInfoV2? ConnectionInfoV2 { get; set; }
        
        public string? ContentType { get; set; }
        
        public string? CreateRoom400ApplicationJSONString { get; set; }
        
        public string? CreateRoom403ApplicationJSONString { get; set; }
        
        public string? CreateRoom404ApplicationJSONString { get; set; }
        
        public string? CreateRoom500ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}