
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.RoomV2
{
    using System;
using System.Net.Http;
using Newtonsoft.Json;
using SDK.Utils;
    
    public class GetRoomInfoRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("roomId")]
        public string RoomId { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, GetRoomInfoRequest value, string baseUrl)
        {
            if("GetRoomInfo" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var roomId = PathParamSerializer.Serialize("simple", false, value.RoomId);
                var message = new HttpRequestMessage(HttpMethod.Get, baseUrl + $"/rooms/v2/{appId}/info/{roomId}");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetRoomInfoRequest]");
        }
    }
}