
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.ProcessesV1
{
    using System;
using System.Net.Http;
using Newtonsoft.Json;
using SDK.Utils;
    
    public class GetProcessInfoRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("processId")]
        public string ProcessId { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, GetProcessInfoRequest value, string baseUrl)
        {
            if("GetProcessInfo" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var processId = PathParamSerializer.Serialize("simple", false, value.ProcessId);
                var message = new HttpRequestMessage(HttpMethod.Get, baseUrl + $"/processes/v1/{appId}/info/{processId}");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetProcessInfoRequest]");
        }
    }
}