
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using System;
using UnityEngine.Networking;
using System.Text;
using Newtonsoft.Json;
using Hathora.Models.Shared;
using Hathora.Utils;
    using System.Collections.Generic;
    public class AppConfig
    {
    /// <summary>
    /// Readable name for an application. Must be unique within an organization.
    /// </summary>
        
        [JsonProperty("appName")]
        public string AppName { get; set; }
        
        
        [JsonProperty("authConfiguration")]
        public AppConfigAuthConfiguration AuthConfiguration { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, AppConfig value, string baseUrl)
        {
            if("CreateApp" == operationId)
            {
                string json = JsonConvert.SerializeObject(value, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});var urlString = baseUrl + "/apps/v1/create";// #request-debugging post TODO: work in progress
                UnityWebRequest message;message = UnityWebRequest.Post(urlString, json, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [AppConfig]");
        }
    }
}