
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
using Hathora.Models.Shared;
    using System.Collections.Generic;
/// <summary>
/// Used to authenticate player requests. Use your own authentication or Hathora's Auth Client.
/// </summary>
    public class ApplicationAuthConfiguration
    {
    /// <summary>
    /// Construct a type with a set of properties K of type T
    /// </summary>
        
        [JsonProperty("anonymous")]
        public RecordStringNever? Anonymous { get; set; }
        
        
        [JsonProperty("google")]
        public ApplicationAuthConfigurationGoogle? Google { get; set; }
        
    /// <summary>
    /// Construct a type with a set of properties K of type T
    /// </summary>
        
        [JsonProperty("nickname")]
        public RecordStringNever? Nickname { get; set; }
        
    }
}