
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    
    public enum CardBrand
    {
    	[JsonProperty("amex")]
		Amex,
		[JsonProperty("cartes_bancaires")]
		CartesBancaires,
		[JsonProperty("diners")]
		Diners,
		[JsonProperty("discover")]
		Discover,
		[JsonProperty("jcb")]
		Jcb,
		[JsonProperty("mastercard")]
		Mastercard,
		[JsonProperty("visa")]
		Visa,
		[JsonProperty("unionpay")]
		Unionpay,
		[JsonProperty("card")]
		Card,
    }
}