
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    public class DeploymentEnv
    {
        
        [JsonProperty("name")]
        public string Name { get; set; }
        
        
        [JsonProperty("value")]
        public string Value { get; set; }
        
    }
}