
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using System;
using Newtonsoft.Json;
    [Obsolete("This enum will be removed in a future release, please migrate away from it as soon as possible")]
    public enum DeploymentTransportType
    {
    	[JsonProperty("tcp")]
		Tcp,
		[JsonProperty("udp")]
		Udp,
		[JsonProperty("tls")]
		Tls,
    }
}