
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
using Hathora.Models.Shared;
    using System.Collections.Generic;
/// <summary>
/// Connection information to an exposed port on an active process.
/// </summary>
    public class ExposedPort
    {
        
        [JsonProperty("host")]
        public string Host { get; set; }
        
        
        [JsonProperty("name")]
        public string Name { get; set; }
        
        
        [JsonProperty("port")]
        public float Port { get; set; }
        
    /// <summary>
    /// Transport type specifies the underlying communication protocol to the exposed port.
    /// </summary>
        
        [JsonProperty("transportType")]
        public TransportType TransportType { get; set; }
        
    }
}