
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Types of lobbies a player can create.
    /// 
    /// <remarks>
    /// 
    /// `private`: the player who created the room must share the roomId with their friends
    /// 
    /// `public`: visible in the public lobby list, anyone can join
    /// 
    /// `local`: for testing with a server running locally
    /// </remarks>
    /// </summary>
    public enum LobbyVisibility
    {
    	[JsonProperty("private")]
		Private,
		[JsonProperty("public")]
		Public,
		[JsonProperty("local")]
		Local,
    }
}