
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
/// <summary>
/// Ok
/// </summary>
    public class LoginResponse
    {
        
        [JsonProperty("token")]
        public string Token { get; set; }
        
    }
}