
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Available metrics to query over time.
    /// </summary>
    public enum MetricName
    {
    	[JsonProperty("cpu")]
		Cpu,
		[JsonProperty("memory")]
		Memory,
		[JsonProperty("rate_egress")]
		RateEgress,
		[JsonProperty("total_egress")]
		TotalEgress,
    }
}