
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Transport type specifies the underlying communication protocol to the exposed port.
    /// </summary>
    public enum TransportType
    {
    	[JsonProperty("tcp")]
		Tcp,
		[JsonProperty("udp")]
		Udp,
		[JsonProperty("tls")]
		Tls,
    }
}