
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Shared
{
    using System;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Utils;
    
    public class AppConfig
    {
    /// <summary>
    /// Readable name for an application. Must be unique within an organization.
    /// </summary>
        
        [JsonProperty("appName")]
        public string AppName { get; set; }
        
        
        [JsonProperty("authConfiguration")]
        public AppConfigAuthConfiguration AuthConfiguration { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, AppConfig value, string baseUrl)
        {
            if("CreateApp" == operationId)
            {
                var message = new HttpRequestMessage(HttpMethod.Post, baseUrl + "/apps/v1/create");

                string json = JsonConvert.SerializeObject(value, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});
                message.Content = new StringContent(json, Encoding.UTF8, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [AppConfig]");
        }
    }
}