
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.DeploymentV1
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using Hathora.Utils;
    using System.Collections.Generic;
    public class GetDeploymentInfoRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("deploymentId")]
        public int DeploymentId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, GetDeploymentInfoRequest value, string baseUrl)
        {
            if("GetDeploymentInfo" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var deploymentId = PathParamSerializer.Serialize("simple", false, value.DeploymentId);var urlString = baseUrl + $"/deployments/v1/{appId}/info/{deploymentId}";var message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [GetDeploymentInfoRequest]");
        }
    }
}