
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.LobbyV2
{
    using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using SDK.Utils;
    
    public class CreateLocalLobbyRequest
    {
        
        [JsonProperty("RequestBody")]
        public CreateLocalLobbyRequestBody RequestBody { get; set; }
        
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("roomId")]
        public string? RoomId { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, CreateLocalLobbyRequest value, string baseUrl)
        {
            if("CreateLocalLobby" == operationId)
            {
                var queryParams = new List<string>();
                
                
                
                queryParams.Add(QueryParamSerializer.Serialize("form",true, "roomId", "", value.RoomId));
                var queryParamString = $"?{String.Join("&", queryParams)}";
                
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var message = new HttpRequestMessage(HttpMethod.Post, baseUrl + $"/lobby/v2/{appId}/create/local" + queryParamString);
                
                
                

                string json = JsonConvert.SerializeObject(value.RequestBody, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});
                message.Content = new StringContent(json, Encoding.UTF8, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [CreateLocalLobbyRequest]");
        }
    }
}