
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.LobbyV2
{
    using System;
using System.Collections.Generic;
using System.Net.Http;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Utils;
    
    public class ListActivePublicLobbiesRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
    /// <summary>
    /// Region to filter by. If omitted, active public lobbies in all regions will be returned.
    /// </summary>
        
        [JsonProperty("region")]
        public Region? Region { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, ListActivePublicLobbiesRequest value, string baseUrl)
        {
            if("ListActivePublicLobbies" == operationId)
            {
                var queryParams = new List<string>();
                
                
                queryParams.Add(QueryParamSerializer.Serialize("form",true, "region", "", value.Region));
                var queryParamString = $"?{String.Join("&", queryParams)}";
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var message = new HttpRequestMessage(HttpMethod.Get, baseUrl + $"/lobby/v2/{appId}/list/public" + queryParamString);
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [ListActivePublicLobbiesRequest]");
        }
    }
}