
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.LogV1
{
    using System;
using System.Collections.Generic;
using UnityEngine.Networking;
using Newtonsoft.Json;
using Hathora.Utils;
    using System.Collections.Generic;
    public class GetLogsForDeploymentRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("deploymentId")]
        public int DeploymentId { get; set; }
        
        
        [JsonProperty("follow")]
        public bool? Follow { get; set; }
        
        
        [JsonProperty("tailLines")]
        public int? TailLines { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, GetLogsForDeploymentRequest value, string baseUrl)
        {
            if("GetLogsForDeployment" == operationId)
            {
                var queryParams = new List<string>();
                
                
                
                queryParams.Add(QueryParamSerializer.Serialize("form",true, "follow", "", value.Follow));
                
                queryParams.Add(QueryParamSerializer.Serialize("form",true, "tailLines", "", value.TailLines));
                var queryParamString = $"?{String.Join("&", queryParams)}";
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var deploymentId = PathParamSerializer.Serialize("simple", false, value.DeploymentId);
                
                var urlString = baseUrl + $"/logs/v1/{appId}/deployment/{deploymentId}" + queryParamString;var message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [GetLogsForDeploymentRequest]");
        }
    }
}