
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.DeploymentV1
{
    using System;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Utils;
    
    public class CreateDeploymentRequest
    {
        
        [JsonProperty("DeploymentConfig")]
        public DeploymentConfig DeploymentConfig { get; set; }
        
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("buildId")]
        public int BuildId { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, CreateDeploymentRequest value, string baseUrl)
        {
            if("CreateDeployment" == operationId)
            {
                
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                var buildId = PathParamSerializer.Serialize("simple", false, value.BuildId);
                var message = new HttpRequestMessage(HttpMethod.Post, baseUrl + $"/deployments/v1/{appId}/create/{buildId}");

                string json = JsonConvert.SerializeObject(value.DeploymentConfig, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});
                message.Content = new StringContent(json, Encoding.UTF8, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [CreateDeploymentRequest]");
        }
    }
}